shell = 'zsh'

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ['defer']

[plugins.zsh-autocomplete]
github = 'marlonrichert/zsh-autocomplete'
apply = ['defer']

